
name: Dev Deploy

on:
  push:
    branches:
      - main


jobs:
  deploy:
    name: Deploy
    runs-on:  ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.AWS_DEV_SSH_USER }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            ls
            cd /home/admin/bikeapp-backend
            git fetch
            git pull
            export NVM_DIR=~/.nvm
            . $NVM_DIR/nvm.sh --install
            npm install
            npm run build
            pm2 restart bikeserver
